version: '3.8'

services:
  backend:
    container_name: bconic_backend_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=postgresql://jeral:1234@bconic_db_container:5432/bconic_db
      - PORT=5000
      - NODE_ENV=development
      - JWT_SECRET=secret
      - POSTGRES_USER=jeral
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bconic_db
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: bconic_db_container
    environment:
      - POSTGRES_USER=jeral
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bconic_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgresql/data
  pgAdmin:
    image: elestio/pgadmin:latest
    container_name: bconic_pgadmin_container
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeral@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5433:80"
    depends_on:
      - postgres
  jenkins:
    image: jenkins/jenkins:latest
    container_name: bconic_jenkins_container
    privileged: true
    restart: always
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./docker_volumes/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  sonarqube:
    image: sonarqube:latest
    container_name: bconic_sonarqube_container
    restart: always
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./docker_volumes/sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./docker_volumes/sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - ./docker_volumes/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
  sonarqube_db:
    image: postgres:13
    container_name: bconic_sonarqube_db_container
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./docker_volumes/postgres_sonarqube:/var/lib/postgresql/data